[package]
name = "wikigrapher"
version = "0.1.0"
authors = ["Rishvic Pushpakaran <rishvic@gmail.com>"]
edition = "2018"
license = "ISC"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
